import type { GuidedSource } from "@/lib/guided/types";

export const guidedSources: GuidedSource[] = [
  {
    id: "fcac-emergency",
    type: "official",
    title: "Setting up an emergency fund",
    publisher: "Financial Consumer Agency of Canada",
    url: "https://www.canada.ca/en/financial-consumer-agency/services/savings-investments/setting-up-emergency-funds.html",
    context: "Government guidance on building a liquid emergency fund.",
    jurisdiction: "Canada",
    reviewed: "2026-07-26",
  },
  {
    id: "fcac-debt",
    type: "official",
    title: "Limiting future debt",
    publisher: "Financial Consumer Agency of Canada",
    url: "https://www.canada.ca/en/financial-consumer-agency/services/debt/limiting-debt.html",
    context: "Government guidance on debt, budgets, and emergency savings.",
    jurisdiction: "Canada",
    reviewed: "2026-07-26",
  },
  {
    id: "cra-tfsa",
    type: "official",
    title: "Tax-Free Savings Account",
    publisher: "Canada Revenue Agency",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/tax-free-savings-account.html",
    context: "Official TFSA rules, contribution room, withdrawals, and tax treatment.",
    jurisdiction: "Canada",
    reviewed: "2026-07-26",
  },
  {
    id: "cra-rrsp",
    type: "official",
    title: "RRSPs and related plans",
    publisher: "Canada Revenue Agency",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/rrsps-related-plans.html",
    context: "Official RRSP contribution, deduction, and withdrawal information.",
    jurisdiction: "Canada",
    reviewed: "2026-07-26",
  },
  {
    id: "cra-fhsa",
    type: "official",
    title: "Participating in your FHSAs",
    publisher: "Canada Revenue Agency",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/first-home-savings-account/contributing-your-fhsa.html",
    context: "Official FHSA participation room and carryforward rules.",
    jurisdiction: "Canada",
    reviewed: "2026-07-26",
  },
  {
    id: "fcac-down-payment",
    type: "official",
    title: "How much you need for a down payment",
    publisher: "Financial Consumer Agency of Canada",
    url: "https://www.canada.ca/en/financial-consumer-agency/services/mortgages/down-payment.html",
    context: "Current federal minimum down payment rules and mortgage insurance context.",
    jurisdiction: "Canada",
    reviewed: "2026-07-26",
  },
  {
    id: "osfi-mqr",
    type: "official",
    title: "Minimum qualifying rate for uninsured mortgages",
    publisher: "Office of the Superintendent of Financial Institutions",
    url: "https://www.osfi-bsif.gc.ca/en/supervision/financial-institutions/banks/minimum-qualifying-rate-uninsured-mortgages",
    context: "The current mortgage stress-test floor for uninsured mortgages.",
    jurisdiction: "Canada",
    effectiveDate: "2026-08-01",
    reviewed: "2026-07-26",
  },
  {
    id: "td-debt-invest",
    type: "educational",
    title: "Should I pay off debt or invest?",
    publisher: "TD Canada Trust",
    url: "https://www.td.com/ca/en/personal-banking/advice/growing-money/should-i-pay-off-debt-or-invest",
    context: "An institution's educational framework for comparing debt repayment and investing.",
    jurisdiction: "Canada",
    reviewed: "2026-07-26",
  },
  {
    id: "td-investing-basics",
    type: "educational",
    title: "Investing 101 basics",
    publisher: "TD Canada Trust",
    url: "https://www.td.com/ca/en/personal-banking/personal-investing/learn/investing-101-basics",
    context: "An institution's overview of saving, investing, goals, risk, and time horizon.",
    jurisdiction: "Canada",
    reviewed: "2026-07-26",
  },
  {
    id: "bmo-affordability",
    type: "educational",
    title: "Mortgage affordability calculator",
    publisher: "Bank of Montreal",
    url: "https://www.bmo.com/main/personal/mortgages/calculators/affordability-calculator/",
    context: "A lender-provided tool for a more detailed affordability estimate.",
    jurisdiction: "Canada",
    reviewed: "2026-07-26",
  },
  {
    id: "scotia-closing",
    type: "educational",
    title: "Understand closing costs in Canada",
    publisher: "Scotiabank",
    url: "https://www.scotiabank.com/ca/en/personal/advice-plus/features/posts.from-offer-to-ownership-understand-closing-costs-in-canada.html",
    context: "An institution's educational estimate of common closing-cost ranges.",
    jurisdiction: "Canada",
    reviewed: "2026-07-26",
  },
  {
    id: "reddit-next-dollar",
    type: "community",
    title: "Emergency fund more important than investing?",
    publisher: "r/PersonalFinanceCanada",
    url: "https://www.reddit.com/r/PersonalFinanceCanada/comments/1tmntuo/emergency_fund_more_important_than_investing/",
    context: "Anecdotal discussion about liquidity, risk, and sequencing. Replies are not verified guidance.",
    jurisdiction: "Community discussion",
    reviewed: "2026-07-26",
  },
  {
    id: "reddit-accounts",
    type: "community",
    title: "Prioritize RRSP contributions now or continue focusing on FHSA and TFSA?",
    publisher: "r/PersonalFinanceCanada",
    url: "https://www.reddit.com/r/PersonalFinanceCanada/comments/1uxdff4/prioritize_rrsp_contributions_now_or_continue/",
    context: "Anecdotal discussion showing how goals, flexibility, and tax context can change the account sequence.",
    jurisdiction: "Community discussion",
    reviewed: "2026-07-26",
  },
  {
    id: "reddit-home",
    type: "community",
    title: "Buying a house",
    publisher: "r/PersonalFinanceCanada",
    url: "https://www.reddit.com/r/PersonalFinanceCanada/comments/1s59of6/buying_a_house/",
    context: "Anecdotal discussion about budgeting beyond the down payment, including closing and emergency costs.",
    jurisdiction: "Community discussion",
    reviewed: "2026-07-26",
  },
  {
    id: "fcac-retirement",
    type: "official",
    title: "Retirement planning",
    publisher: "Financial Consumer Agency of Canada",
    url: "https://www.canada.ca/en/financial-consumer-agency/services/retirement-planning.html",
    context: "Government guidance on retirement goals, income sources, expenses, and planning tools.",
    jurisdiction: "Canada",
    reviewed: "2026-08-01",
  },
  {
    id: "cpp-payments",
    type: "official",
    title: "CPP retirement pension: How much you could receive",
    publisher: "Service Canada",
    url: "https://www.canada.ca/en/services/benefits/publicpensions/cpp/payment-amounts.html",
    context: "Official CPP amount information and factors that affect an individual's benefit.",
    jurisdiction: "Canada outside Quebec",
    reviewed: "2026-08-01",
    effectiveDate: "2026",
  },
  {
    id: "oas",
    type: "official",
    title: "Old Age Security pension",
    publisher: "Service Canada",
    url: "https://www.canada.ca/en/services/benefits/publicpensions/cpp/old-age-security.html",
    context: "Official OAS eligibility, payment, and recovery-tax information.",
    jurisdiction: "Canada",
    reviewed: "2026-08-01",
  },
  {
    id: "fcac-prepayment",
    type: "official",
    title: "Paying off your mortgage faster",
    publisher: "Financial Consumer Agency of Canada",
    url: "https://www.canada.ca/en/financial-consumer-agency/services/mortgages/pay-mortgage-faster.html",
    context: "Government guidance on prepayment privileges, charges, and ways to shorten amortization.",
    jurisdiction: "Canada",
    reviewed: "2026-08-01",
  },
  {
    id: "cra-room",
    type: "official",
    title: "Savings and pension plan administration",
    publisher: "Canada Revenue Agency",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/savings-pension-plans.html",
    context: "Official entry point for current TFSA, RRSP, FHSA, and related plan rules.",
    jurisdiction: "Canada",
    reviewed: "2026-08-01",
  },
  {
    id: "fcac-homebuying",
    type: "official",
    title: "Buying a home",
    publisher: "Financial Consumer Agency of Canada",
    url: "https://www.canada.ca/en/financial-consumer-agency/services/buying-home.html",
    context: "Government guidance covering affordability, mortgages, upfront costs, and ongoing ownership costs.",
    jurisdiction: "Canada",
    reviewed: "2026-08-01",
  },
  {
    id: "fcac-debt-help",
    type: "official",
    title: "Getting help from a credit counsellor",
    publisher: "Financial Consumer Agency of Canada",
    url: "https://www.canada.ca/en/financial-consumer-agency/services/debt/debt-help.html",
    context: "Government guidance on credit counselling, debt management plans, fees, and questions to ask.",
    jurisdiction: "Canada",
    reviewed: "2026-08-01",
  },
  {
    id: "osb-lit",
    type: "official",
    title: "What is a Licensed Insolvency Trustee?",
    publisher: "Office of the Superintendent of Bankruptcy Canada",
    url: "https://ised-isde.canada.ca/site/office-superintendent-bankruptcy/en/you-owe-money/what-licensed-insolvency-trustee",
    context: "Official explanation of the regulated professionals authorized to administer consumer proposals and bankruptcies.",
    jurisdiction: "Canada",
    reviewed: "2026-08-01",
  },
  {
    id: "reddit-retirement",
    type: "community",
    title: "Retirement planning discussion",
    publisher: "r/PersonalFinanceCanada",
    url: "https://www.reddit.com/r/PersonalFinanceCanada/comments/13zwkrc/retirement_planning/",
    context: "Anecdotal perspectives on retirement assumptions and planning. Replies are not verified guidance.",
    jurisdiction: "Community discussion",
    reviewed: "2026-08-01",
  },
  {
    id: "reddit-mortgage",
    type: "community",
    title: "Mortgage versus investing discussion",
    publisher: "r/PersonalFinanceCanada",
    url: "https://www.reddit.com/r/PersonalFinanceCanada/comments/1u48pou/pay_off_mortgage_or_invest/",
    context: "Anecdotal perspectives about certainty, leverage, liquidity, and investing. Replies are not verified guidance.",
    jurisdiction: "Community discussion",
    reviewed: "2026-08-01",
  },
];

export function getGuidedSources(ids: string[]) {
  return ids
    .map((id) => guidedSources.find((source) => source.id === id))
    .filter((source): source is GuidedSource => Boolean(source));
}
