import type { GuidedSource } from "@/lib/guided/types";

export const guidedSources: GuidedSource[] = [
  {
    id: "fcac-emergency",
    type: "official",
    title: "Setting up an emergency fund",
    publisher: "Financial Consumer Agency of Canada",
    url: "https://www.canada.ca/en/financial-consumer-agency/services/savings-investments/setting-up-emergency-funds.html",
    context: "Government guidance on building a liquid emergency fund.",
    reviewed: "2026-07-26",
  },
  {
    id: "fcac-debt",
    type: "official",
    title: "Limiting future debt",
    publisher: "Financial Consumer Agency of Canada",
    url: "https://www.canada.ca/en/financial-consumer-agency/services/debt/limiting-debt.html",
    context: "Government guidance on debt, budgets, and emergency savings.",
    reviewed: "2026-07-26",
  },
  {
    id: "cra-tfsa",
    type: "official",
    title: "Tax-Free Savings Account",
    publisher: "Canada Revenue Agency",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/tax-free-savings-account.html",
    context: "Official TFSA rules, contribution room, withdrawals, and tax treatment.",
    reviewed: "2026-07-26",
  },
  {
    id: "cra-rrsp",
    type: "official",
    title: "RRSPs and related plans",
    publisher: "Canada Revenue Agency",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/rrsps-related-plans.html",
    context: "Official RRSP contribution, deduction, and withdrawal information.",
    reviewed: "2026-07-26",
  },
  {
    id: "cra-fhsa",
    type: "official",
    title: "Participating in your FHSAs",
    publisher: "Canada Revenue Agency",
    url: "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/first-home-savings-account/contributing-your-fhsa.html",
    context: "Official FHSA participation room and carryforward rules.",
    reviewed: "2026-07-26",
  },
  {
    id: "fcac-down-payment",
    type: "official",
    title: "How much you need for a down payment",
    publisher: "Financial Consumer Agency of Canada",
    url: "https://www.canada.ca/en/financial-consumer-agency/services/mortgages/down-payment.html",
    context: "Current federal minimum down payment rules and mortgage insurance context.",
    reviewed: "2026-07-26",
  },
  {
    id: "osfi-mqr",
    type: "official",
    title: "Minimum qualifying rate for uninsured mortgages",
    publisher: "Office of the Superintendent of Financial Institutions",
    url: "https://www.osfi-bsif.gc.ca/en/supervision/financial-institutions/banks/minimum-qualifying-rate-uninsured-mortgages",
    context: "The current mortgage stress-test floor for uninsured mortgages.",
    reviewed: "2026-07-26",
  },
  {
    id: "td-debt-invest",
    type: "educational",
    title: "Should I pay off debt or invest?",
    publisher: "TD Canada Trust",
    url: "https://www.td.com/ca/en/personal-banking/advice/growing-money/should-i-pay-off-debt-or-invest",
    context: "An institution's educational framework for comparing debt repayment and investing.",
    reviewed: "2026-07-26",
  },
  {
    id: "td-investing-basics",
    type: "educational",
    title: "Investing 101 basics",
    publisher: "TD Canada Trust",
    url: "https://www.td.com/ca/en/personal-banking/personal-investing/learn/investing-101-basics",
    context: "An institution's overview of saving, investing, goals, risk, and time horizon.",
    reviewed: "2026-07-26",
  },
  {
    id: "bmo-affordability",
    type: "educational",
    title: "Mortgage affordability calculator",
    publisher: "Bank of Montreal",
    url: "https://www.bmo.com/main/personal/mortgages/calculators/affordability-calculator/",
    context: "A lender-provided tool for a more detailed affordability estimate.",
    reviewed: "2026-07-26",
  },
  {
    id: "scotia-closing",
    type: "educational",
    title: "Understand closing costs in Canada",
    publisher: "Scotiabank",
    url: "https://www.scotiabank.com/ca/en/personal/advice-plus/features/posts.from-offer-to-ownership-understand-closing-costs-in-canada.html",
    context: "An institution's educational estimate of common closing-cost ranges.",
    reviewed: "2026-07-26",
  },
  {
    id: "reddit-next-dollar",
    type: "community",
    title: "Emergency fund more important than investing?",
    publisher: "r/PersonalFinanceCanada",
    url: "https://www.reddit.com/r/PersonalFinanceCanada/comments/1tmntuo/emergency_fund_more_important_than_investing/",
    context: "Anecdotal discussion about liquidity, risk, and sequencing. Replies are not verified guidance.",
    reviewed: "2026-07-26",
  },
  {
    id: "reddit-accounts",
    type: "community",
    title: "Prioritize RRSP contributions now or continue focusing on FHSA and TFSA?",
    publisher: "r/PersonalFinanceCanada",
    url: "https://www.reddit.com/r/PersonalFinanceCanada/comments/1uxdff4/prioritize_rrsp_contributions_now_or_continue/",
    context: "Anecdotal discussion showing how goals, flexibility, and tax context can change the account sequence.",
    reviewed: "2026-07-26",
  },
  {
    id: "reddit-home",
    type: "community",
    title: "Buying a house",
    publisher: "r/PersonalFinanceCanada",
    url: "https://www.reddit.com/r/PersonalFinanceCanada/comments/1s59of6/buying_a_house/",
    context: "Anecdotal discussion about budgeting beyond the down payment, including closing and emergency costs.",
    reviewed: "2026-07-26",
  },
];

export function getGuidedSources(ids: string[]) {
  return ids
    .map((id) => guidedSources.find((source) => source.id === id))
    .filter((source): source is GuidedSource => Boolean(source));
}
